### ISSUE TITLE
do ya need help with dat

### ISSUE THREAD

**Issue by wael444** [synthun/xinitman#1]

**Comment by synthun** [comment]
no thanks much love

**Comment by wael444** [comment]
my eyes literally burning rn but alr enjoy

**Comment by synthun** [comment]
![image](https://user-images.githubusercontent.com/84999468/183223476-ce821ae3-8c35-400d-9e8c-b07ce422def8.png)

**Comment by synthun** [comment]
![image](https://user-images.githubusercontent.com/84999468/183223491-74f84e80-f48d-4fcf-9934-df59d3268d07.png)

**Comment by synthun** [comment]
![2022-08-05-193159_747x730_scrot](https://user-images.githubusercontent.com/84999468/183223509-5701b95c-90c5-45e0-89fb-cc9452bfbc85.png)
